Repository nextcloud-libraries/nextcloud-paths, pull requests merged in 2024-07, with the labels that each got.

#678 Add SPDX header
  .github/dependabot.yml
  .github/workflows/reuse.yml
  .gitignore
  AUTHORS.md
  CHANGELOG.md
  LICENSES/CC0-1.0.txt
  LICENSES/GPL-3.0-or-later.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  lib/index.ts
  test/basename.test.ts
  test/dirname.test.ts
  test/isSamePath.test.ts
  test/joinPaths.test.ts
  vite.config.ts
  vitest.config.ts
Labels: documentation, 3. to review

#679 chore: Prepare 2.2.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#680 fix: Correctly setup Typescript root to emit declarations
  REUSE.toml
  package-lock.json
  package.json
  test/tsconfig.json
  tsconfig.json
  vitest.config.ts
Labels: bug, 3. to review

#681 chore: Prepare v2.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review
