Repository nextcloud-libraries/nextcloud-paths, pull requests merged in 2024-04, with the labels that each got.

#338 Update npm and node engines versions
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#654 fix: Add example of `joinPaths` to README, remove non existing travis
  .npmignore
  .travis.yml
  README.md
  package.json
Labels: 3. to review

#653 feat: Migrate to use Vite - drop Babel and Jest
  .github/workflows/node-test.yml
  babel.config.js
  package-lock.json
  package.json
  test/basename.test.js
  test/basename.test.ts
  test/dirname.test.js
  test/dirname.test.ts
  test/isSamePath.test.js
  test/isSamePath.test.ts
  test/joinPaths.test.js
  test/joinPaths.test.ts
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: enhancement, 3. to review
